name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  IMAGE_NAME: btcprice
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  RUN_NUM: ${{github.run_number}}

jobs:

  build:

    runs-on: ubuntu-latest
        

    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub 

      run: | 
        echo run number is $RUN_NUM
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Log in to Docker Hub
      run: |
          docker build . --file Dockerfile --tag btcprice:$RUN_NUM
    - name: Push to Docker Hub
      run: |
        echo $RUN_NUM

        docker tag btcprice bryanlimkt/btcprice:$RUN_NUM
        docker tag myhello bryanlimkt/btcprice:latest
        docker push btcprice:$RUN_NUM
        docker push btcprice:latest
