name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  IMAGE_NAME: btcprice
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  VERSION_NUM: ${{github.run_number}} - 41

jobs:

  build:

    runs-on: ubuntu-latest
        

    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub 

      run: | 
        echo run number is $VERSION_NUM
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Log in to Docker Hub
      run: |
          docker build . --file Dockerfile --tag btcprice:$VERSION_NUM
    - name: Push to Docker Hub
      run: |
        echo $VERSION_NUM

        docker tag btcprice bryanlimkt/btcprice:$VERSION_NUM
        docker tag btcprice bryanlimkt/btcprice:latest
        docker push btcprice:$VERSION_NUM
        docker push btcprice:latest
