name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  IMAGE_NAME: btcprice
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:

  build:

    runs-on: ubuntu-latest
        

    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub 

      run: | 
        echo ${{github.run.id}}
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Log in to Docker Hub
      run: |
          docker build . --file Dockerfile --tag btcprice:${{github.run.id}}
    - name: Push to Docker Hub
      run: |
        echo ${{github.run.id}}

        docker tag btcprice bryanlimkt/btcprice:${{github.run.id}}
        docker tag myhello bryanlimkt/btcprice:latest
        docker push btcprice:${{github.run.id}}
        docker push btcprice:latest
